#
# GitHub Action test
#
# Created by Denis Konieiev
# 
name: My-GitHubActions-Test
env:
  APPLICATION_NAME       : "MyFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha }}"   

on: 
  push:
    branches: 
      - master

jobs:

  first_test_job:
    runs-on: ubuntu-latest
   
    steps:
      - name: Print Hello Message from Testing job
        run : echo "Hello World from Testing job"
      
      - name : Execute few commands
        run  : |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
    
    
  my_deploy:
    runs-on: ubuntu-latest
    needs  : [first_test_job]
    
    steps:
      - name: Print Hello Message from Deploy job
        run : echo "Hello World from Deploy job"
      
      - name: Printing Deployment package
        run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
    

